### PR TITLE
fix(deps): update dependencies

### PR DESCRIPTION
**Pull request by anehx**

### CODE REVIEW

**Comment by luytena** [comment]
@anehx Quick note before I've had a chance to review: Thanks for updating! Before merging, I'd like to check the compatibility with different release states in eBau.

**Comment by anehx** [comment]
> @anehx Quick note before I've had a chance to review: Thanks for updating! Before merging, I'd like to check the compatibility with different release states in eBau.

That's the reason for this. In order to update caluma etc. we need this update.

**Review by derrabauke — APPROVED** [review]
ogog :dash:

**Comment by luytena** [comment]
> After discussion with @luytena we agreed that we'll not merge this until the next bugfix is implemented, released and tested.
> 
> **Please do not merge this PR before @luytena gives her OK.**

Let's merge it.

**Review by luytena — APPROVED** [review]

**Pull request merged**
